# Generated by Django 5.1.3 on 2024-11-28 11:34

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=100)),
                ('salary', models.IntegerField(max_length=100)),
                ('image', models.ImageField(upload_to=pages.models.upload_employee_image)),
            ],
        ),
    ]
